apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eks-test
  name: eks-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: eks-test
  type: LoadBalancer
status:
  loadBalancer: {}