apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eks-test
  name: eks-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eks-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eks-test
    spec:
      containers:
      - image: eproject/web
        name: web
        ports:
        - containerPort: 200
        resources: {}
status: {}